export const LanguageCode = {
	EN: "en",
	JA: "ja",
	KO: "ko",
	ZH: "zh",
	ES: "es",
	FR: "fr",
	DE: "de",
	IT: "it",
	PT: "pt",
	RU: "ru",
	AR: "ar",
	HI: "hi",
	TH: "th",
	VI: "vi",
	ID: "id",
	MS: "ms",
	TL: "tl",
	TR: "tr",
	NL: "nl",
	UK: "uk",
	PL: "pl",
	RO: "ro",
	EL: "el",
	CS: "cs",
	FI: "fi",
	BG: "bg",
	DA: "da",
	SK: "sk",
	SV: "sv",
	HR: "hr",
	HU: "hu",
	NO: "no",
	SL: "sl",
	CA: "ca",
	LT: "lt",
	NN: "nn",
	HE: "he",
	FA: "fa",
	AF: "af",
	TA: "ta",
} as const;

export type LanguageCode = (typeof LanguageCode)[keyof typeof LanguageCode];

export interface LanguageInfo {
	code: LanguageCode;
	name: string;
	nativeName: string;
	translationName: string; // Name passed to LLM for translation
	supportsQwenTTS: boolean;
	supportsMiniMaxTTS: boolean;
}

export const LANGUAGE_MAP: Record<LanguageCode, LanguageInfo> = {
	[LanguageCode.EN]: {
		code: LanguageCode.EN,
		name: "English",
		nativeName: "English",
		translationName: "English",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.JA]: {
		code: LanguageCode.JA,
		name: "Japanese",
		nativeName: "日本語",
		translationName: "Japanese",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.KO]: {
		code: LanguageCode.KO,
		name: "Korean",
		nativeName: "한국어",
		translationName: "Korean",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.ZH]: {
		code: LanguageCode.ZH,
		name: "Chinese",
		nativeName: "中文",
		translationName: "Chinese (Mandarin / Cantonese)",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.ES]: {
		code: LanguageCode.ES,
		name: "Spanish",
		nativeName: "Español",
		translationName: "Spanish",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.FR]: {
		code: LanguageCode.FR,
		name: "French",
		nativeName: "Français",
		translationName: "French",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.DE]: {
		code: LanguageCode.DE,
		name: "German",
		nativeName: "Deutsch",
		translationName: "German",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.IT]: {
		code: LanguageCode.IT,
		name: "Italian",
		nativeName: "Italiano",
		translationName: "Italian",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.PT]: {
		code: LanguageCode.PT,
		name: "Portuguese",
		nativeName: "Português",
		translationName: "Portuguese (Brazilian)",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.RU]: {
		code: LanguageCode.RU,
		name: "Russian",
		nativeName: "Русский",
		translationName: "Russian",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.AR]: {
		code: LanguageCode.AR,
		name: "Arabic",
		nativeName: "العربية",
		translationName: "Arabic",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.HI]: {
		code: LanguageCode.HI,
		name: "Hindi",
		nativeName: "हिन्दी",
		translationName: "Hindi",
		supportsQwenTTS: true,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.TH]: {
		code: LanguageCode.TH,
		name: "Thai",
		nativeName: "ไทย",
		translationName: "Thai",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.VI]: {
		code: LanguageCode.VI,
		name: "Vietnamese",
		nativeName: "Tiếng Việt",
		translationName: "Vietnamese",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.ID]: {
		code: LanguageCode.ID,
		name: "Indonesian",
		nativeName: "Bahasa Indonesia",
		translationName: "Indonesian",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.MS]: {
		code: LanguageCode.MS,
		name: "Malay",
		nativeName: "Bahasa Melayu",
		translationName: "Malay",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.TL]: {
		code: LanguageCode.TL,
		name: "Filipino",
		nativeName: "Filipino",
		translationName: "Filipino",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.TR]: {
		code: LanguageCode.TR,
		name: "Turkish",
		nativeName: "Türkçe",
		translationName: "Turkish",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.NL]: {
		code: LanguageCode.NL,
		name: "Dutch",
		nativeName: "Nederlands",
		translationName: "Dutch",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.UK]: {
		code: LanguageCode.UK,
		name: "Ukrainian",
		nativeName: "Українська",
		translationName: "Ukrainian",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.PL]: {
		code: LanguageCode.PL,
		name: "Polish",
		nativeName: "Polski",
		translationName: "Polish",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.RO]: {
		code: LanguageCode.RO,
		name: "Romanian",
		nativeName: "Română",
		translationName: "Romanian",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.EL]: {
		code: LanguageCode.EL,
		name: "Greek",
		nativeName: "Ελληνικά",
		translationName: "Greek",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.CS]: {
		code: LanguageCode.CS,
		name: "Czech",
		nativeName: "Čeština",
		translationName: "Czech",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.FI]: {
		code: LanguageCode.FI,
		name: "Finnish",
		nativeName: "Suomi",
		translationName: "Finnish",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.BG]: {
		code: LanguageCode.BG,
		name: "Bulgarian",
		nativeName: "Български",
		translationName: "Bulgarian",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.DA]: {
		code: LanguageCode.DA,
		name: "Danish",
		nativeName: "Dansk",
		translationName: "Danish",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.SK]: {
		code: LanguageCode.SK,
		name: "Slovak",
		nativeName: "Slovenčina",
		translationName: "Slovak",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.SV]: {
		code: LanguageCode.SV,
		name: "Swedish",
		nativeName: "Svenska",
		translationName: "Swedish",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.HR]: {
		code: LanguageCode.HR,
		name: "Croatian",
		nativeName: "Hrvatski",
		translationName: "Croatian",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.HU]: {
		code: LanguageCode.HU,
		name: "Hungarian",
		nativeName: "Magyar",
		translationName: "Hungarian",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.NO]: {
		code: LanguageCode.NO,
		name: "Norwegian",
		nativeName: "Norsk",
		translationName: "Norwegian",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.SL]: {
		code: LanguageCode.SL,
		name: "Slovenian",
		nativeName: "Slovenščina",
		translationName: "Slovenian",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.CA]: {
		code: LanguageCode.CA,
		name: "Catalan",
		nativeName: "Català",
		translationName: "Catalan",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.LT]: {
		code: LanguageCode.LT,
		name: "Lithuanian",
		nativeName: "Lietuvių",
		translationName: "Lithuanian",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.NN]: {
		code: LanguageCode.NN,
		name: "Nynorsk",
		nativeName: "Nynorsk",
		translationName: "Nynorsk",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.HE]: {
		code: LanguageCode.HE,
		name: "Hebrew",
		nativeName: "עברית",
		translationName: "Hebrew",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.FA]: {
		code: LanguageCode.FA,
		name: "Persian",
		nativeName: "فارسی",
		translationName: "Persian",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.AF]: {
		code: LanguageCode.AF,
		name: "Afrikaans",
		nativeName: "Afrikaans",
		translationName: "Afrikaans",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
	[LanguageCode.TA]: {
		code: LanguageCode.TA,
		name: "Tamil",
		nativeName: "தமிழ்",
		translationName: "Tamil",
		supportsQwenTTS: false,
		supportsMiniMaxTTS: true,
	},
};

export const SUPPORTED_LANGUAGES = Object.values(LanguageCode);

export const QWEN_TTS_SUPPORTED_LANGUAGES = Object.values(LANGUAGE_MAP)
	.filter((info) => info.supportsQwenTTS)
	.map((info) => info.code);

export const MINIMAX_TTS_SUPPORTED_LANGUAGES = Object.values(LANGUAGE_MAP)
	.filter((info) => info.supportsMiniMaxTTS)
	.map((info) => info.code);